from datetime import datetime
from utils.analyzer import ReviewResult


def generate_markdown_report(result: ReviewResult, code_source: str = "pasted code") -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append(f"# VibeAudit Report")
    lines.append(f"**Reviewed:** {code_source}")
    lines.append(f"**Date:** {now}")
    lines.append(f"**Overall Score:** {result.overall_score}/100 — {result.overall_label}")
    lines.append(f"**Safe to ship:** {'Yes' if result.is_safe_to_ship else 'No — fix critical/high issues first'}")
    lines.append("")

    lines.append("## Scores")
    lines.append(f"| Category | Score | Status |")
    lines.append(f"|----------|-------|--------|")
    lines.append(f"| Security | {result.security_score}/100 | {_score_emoji(result.security_score)} |")
    lines.append(f"| Logic    | {result.logic_score}/100 | {_score_emoji(result.logic_score)} |")
    lines.append(f"| Scale    | {result.scale_score}/100 | {_score_emoji(result.scale_score)} |")
    lines.append(f"| Quality  | {result.quality_score}/100 | {_score_emoji(result.quality_score)} |")
    lines.append(f"| **Overall** | **{result.overall_score}/100** | {_score_emoji(result.overall_score)} |")
    lines.append("")

    lines.append("## Issue Summary")
    lines.append(f"- 🔴 Critical: {result.critical_count}")
    lines.append(f"- 🟠 High: {result.high_count}")
    lines.append(f"- 🟡 Medium: {result.medium_count}")
    lines.append(f"- 🟢 Low: {result.low_count}")
    lines.append(f"- **Total: {len(result.issues)}**")
    lines.append("")

    if result.verdict:
        lines.append("## Verdict")
        lines.append(result.verdict)
        lines.append("")

    categories = ["security", "logic", "scalability", "quality"]
    labels = {
        "security": "Security Issues",
        "logic": "Logic Issues",
        "scalability": "Scalability Issues",
        "quality": "Code Quality Issues"
    }

    for cat in categories:
        cat_issues = [i for i in result.issues if i.category == cat]
        lines.append(f"## {labels[cat]}")
        if not cat_issues:
            lines.append("No issues found.")
        else:
            for issue in cat_issues:
                lines.append(f"### {issue.name}")
                lines.append(f"**Severity:** {issue.severity}")
                lines.append(f"**Location:** {issue.line_ref}")
                lines.append(f"**Problem:** {issue.explanation}")
                lines.append(f"**Fix:** {issue.fix}")
                lines.append("")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by VibeAudit — github.com/SREEGEETHES/vibeaudit*")

    return "\n".join(lines)


def _score_emoji(score: int) -> str:
    if score >= 90: return "Excellent"
    if score >= 75: return "Good"
    if score >= 60: return "Needs Work"
    if score >= 40: return "Risky"
    return "Do Not Ship"